title: **Rex Bias** | Aspiring Pentester | Seeking Entry-Level Security Testing Position Security+ | CCNA | Network+ 
logo: assets/img/Headshots.JPEG
description: I identify and mitigate security risks in digital environments.
#show_downloads: true
theme: jekyll-theme-minimal
