title: Rex Bias | Technical Support Engineer | Security+ | CCNA | Network+ 
logo: assets/img/Headshots.JPEG
description: It’s not just about fixing issues; it’s about empowering users to understand and navigate the digital world with ease.
#show_downloads: true
theme: jekyll-theme-minimal
