title: Rex Bias
Aspiring Pentester | Seeking Entry-Level Security Testing Position
Security+ | CCNA | Network+
I identify and mitigate security risks in digital environments.
logo: assets/img/Headshots.JPEG
#description: Gregarious adventurer with a passion for all things cyber.
#show_downloads: true
theme: jekyll-theme-minimal
