title:      Rex Bias       Security+ | CCNA | Network+ 
logo: assets/img/Headshots.JPEG
description: It’s not just about fixing issues; it’s about empowering users to understand and navigate the digital world easily.
#URL: "https://www.youtube.com/@rexbias7201/featured"
#show_downloads: true
theme: jekyll-theme-minimal
